"""
Patient Billing Auditor for HealthFraudML.

Analyzes patient bills for upcoding, unbundling, and price gouging.
Provides human-readable explanations and generates a dispute letter.
"""

import csv
import os
from typing import List, Dict, Any, Optional

# Path to the expanded CMS PFS price benchmark (code numbers + national
# Medicare payment amounts only; no AMA CPT descriptions). Generated by
# scripts/build_cms_benchmark.py from the official CMS PFS Relative Value File.
_CMS_BENCHMARK_PATH = os.path.join(os.path.dirname(__file__), "data", "cms_pfs_benchmark.csv")

# Plain-language names for billing codes: public-domain HCPCS Level II
# descriptions from CMS, plus project-authored paraphrases for numeric CPT
# codes (labelled "(unofficial name)" in output — never AMA descriptors).
# Generated by scripts/build_code_names.py.
_CODE_NAMES_PATH = os.path.join(os.path.dirname(__file__), "data", "code_names.csv")


def _load_code_names() -> Dict[str, Dict[str, str]]:
    """Load code -> {"plain_name", "source"} from the code-names data file."""
    names: Dict[str, Dict[str, str]] = {}
    if not os.path.isfile(_CODE_NAMES_PATH):
        return names
    try:
        with open(_CODE_NAMES_PATH, newline="", encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                code = (row.get("code") or "").strip()
                name = (row.get("plain_name") or "").strip()
                if code and name:
                    names[code] = {
                        "plain_name": name,
                        "source": (row.get("source") or "").strip(),
                    }
    except OSError:
        pass
    return names


def _load_cms_benchmark() -> Dict[str, Dict[str, Any]]:
    """Load the CMS price benchmark CSV into a code -> pricing dict.

    Entries are price-only (medicare_min/max, fair_min/max). They carry no
    ``description`` or ``severity`` — those stay with the curated built-ins.
    Returns an empty dict if the benchmark file is absent (e.g. dev checkout
    before the data file is generated).
    """
    benchmark: Dict[str, Dict[str, Any]] = {}
    if not os.path.isfile(_CMS_BENCHMARK_PATH):
        return benchmark
    try:
        with open(_CMS_BENCHMARK_PATH, newline="", encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                code = (row.get("cpt_code") or "").strip()
                if not code:
                    continue
                try:
                    benchmark[code] = {
                        "medicare_min": float(row["medicare_min"]),
                        "medicare_max": float(row["medicare_max"]),
                        "fair_min": float(row["fair_min"]),
                        "fair_max": float(row["fair_max"]),
                    }
                except (KeyError, ValueError):
                    continue
    except OSError:
        pass
    return benchmark


class BillingAuditor:
    """
    Audits a list of billed line items for potential billing anomalies.
    """

    # Curated built-in reference for common codes. These carry full metadata
    # (description + severity) used by the upcoding/unbundling logic.
    # Columns: CPT code -> {description, medicare_min, medicare_max, fair_min, fair_max, severity}
    # Severity ranges from 1 (minor) to 5 (critical/severe)
    _BUILTIN_CPT_REFERENCE = {
        "99285": {
            "description": "Emergency Department Visit, Level 5 (High Severity/Complexity)",
            "medicare_min": 150.0,
            "medicare_max": 250.0,
            "fair_min": 1500.0,
            "fair_max": 3500.0,
            "severity": 5,
        },
        "99284": {
            "description": "Emergency Department Visit, Level 4 (High/Moderate Severity)",
            "medicare_min": 120.0,
            "medicare_max": 180.0,
            "fair_min": 1000.0,
            "fair_max": 2200.0,
            "severity": 4,
        },
        "99283": {
            "description": "Emergency Department Visit, Level 3 (Moderate Severity)",
            "medicare_min": 80.0,
            "medicare_max": 120.0,
            "fair_min": 500.0,
            "fair_max": 1200.0,
            "severity": 3,
        },
        "99282": {
            "description": "Emergency Department Visit, Level 2 (Low/Moderate Severity)",
            "medicare_min": 50.0,
            "medicare_max": 80.0,
            "fair_min": 300.0,
            "fair_max": 700.0,
            "severity": 2,
        },
        "99281": {
            "description": "Emergency Department Visit, Level 1 (Low Severity)",
            "medicare_min": 30.0,
            "medicare_max": 50.0,
            "fair_min": 150.0,
            "fair_max": 400.0,
            "severity": 1,
        },
        "56420": {
            "description": "Incision and Drainage of Bartholin's Gland Abscess/Cyst",
            "medicare_min": 115.0,
            "medicare_max": 200.0,
            "fair_min": 400.0,
            "fair_max": 1200.0,
            "severity": 2,
        },
        "12001": {
            "description": "Simple Repair of Superficial Wound (2.5 cm or less)",
            "medicare_min": 80.0,
            "medicare_max": 130.0,
            "fair_min": 300.0,
            "fair_max": 800.0,
            "severity": 1,
        },
        "12002": {
            "description": "Simple Repair of Superficial Wound (2.6 cm to 7.5 cm)",
            "medicare_min": 100.0,
            "medicare_max": 160.0,
            "fair_min": 400.0,
            "fair_max": 1000.0,
            "severity": 2,
        },
        "99214": {
            "description": "Office/Outpatient Visit, Established Patient, 30-39 minutes",
            "medicare_min": 100.0,
            "medicare_max": 140.0,
            "fair_min": 200.0,
            "fair_max": 450.0,
            "severity": 3,
        },
        "99215": {
            "description": "Office/Outpatient Visit, Established Patient, 40-54 minutes",
            "medicare_min": 150.0,
            "medicare_max": 200.0,
            "fair_min": 300.0,
            "fair_max": 600.0,
            "severity": 4,
        },
    }

    # Full reference = CMS price benchmark (thousands of codes, price-only)
    # overlaid by the curated built-ins (which win, and add description +
    # severity). Price-only entries get benchmarking but never trigger
    # severity-based upcoding.
    CPT_REFERENCE = {**_load_cms_benchmark(), **_BUILTIN_CPT_REFERENCE}

    # code -> {"plain_name", "source"}; see _load_code_names().
    CODE_NAMES = _load_code_names()

    #: Human-readable provenance for each name source, shown in reports so a
    #: reader can tell where a description came from without asking.
    NAME_SOURCE_LABELS = {
        "bill": "as written on your bill",
        "curated": "project-written name (unofficial)",
        "cms_hcpcs_l2": "official CMS HCPCS Level II description",
        "authored": "project-written name (unofficial)",
        "none": "no description available",
    }

    @staticmethod
    def code_system(code: str) -> str:
        """'CPT' for numeric Level I codes, 'HCPCS' for letter-prefixed Level II.

        Calling a J- or G-code "CPT" in a letter to a billing department is
        wrong on its face and invites the whole letter being dismissed.
        """
        return "CPT" if str(code).strip()[:1].isdigit() else "HCPCS"

    @classmethod
    def code_name_source(cls, cpt_code: str) -> Optional[str]:
        """Where this code's name came from: 'cms_hcpcs_l2', 'authored', or None."""
        entry = cls.CODE_NAMES.get(str(cpt_code).strip())
        return entry.get("source") or None if entry else None

    @classmethod
    def _name_suffix(cls, cpt_code: str) -> str:
        """`` (Name)`` for use inside finding messages, or '' if we have none."""
        name = cls.code_name(cpt_code)
        return f" ({name})" if name else ""

    @classmethod
    def code_name(cls, cpt_code: str) -> Optional[str]:
        """Display name for a code, or None if we have no name for it.

        Authored (non-official) CPT paraphrases are marked so a reader never
        mistakes them for the official AMA descriptor.
        """
        entry = cls.CODE_NAMES.get(str(cpt_code).strip())
        if not entry:
            return None
        name = entry["plain_name"]
        if entry.get("source") == "authored":
            name = f"{name} (unofficial name)"
        return name

    def __init__(self, provider_name: str = "Unknown Provider", db: Optional[Any] = None):
        self.provider_name = provider_name
        self.db = db

    def audit_bill(self, items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Audit a list of billed items.

        Parameters
        ----------
        items : list of dict
            Each dict should have:
            - 'cpt_code': str (e.g. '99285')
            - 'amount': float (the billed charge, e.g. 6672.0)
            - 'description': str, optional

        Returns
        -------
        dict
            Contains audited items, detected flags, overall risk,
            explanations, and a dispute letter.
        """
        if not items:
            return {
                "provider_name": self.provider_name,
                "total_billed": 0.0,
                "suggested_savings": 0.0,
                "risk_level": "Low",
                "audited_items": [],
                "findings": [],
                "dispute_letter": "",
            }

        audited_items = []
        findings = []
        has_upcoding = False
        has_unbundling = False
        has_overpricing = False
        total_billed = sum(float(item.get("amount", 0.0)) for item in items)
        
        # Track savings per index to prevent double counting
        item_savings = [0.0] * len(items)

        # Separate E/M visits and procedures
        em_items = []
        procedure_items = []

        for idx, item in enumerate(items):
            cpt = str(item.get("cpt_code", "")).strip()
            amount = float(item.get("amount", 0.0))
            desc = item.get("description", "")

            ref = None
            # Try database lookup
            if self.db:
                db_rule = self.db.get_rule(cpt)
                if db_rule:
                    ref = db_rule
                elif desc:
                    # Semantic search to resolve unknown/missing code to CPT
                    matches = self.db.query_by_description(desc, n_results=1)
                    if matches and matches[0]["similarity_distance"] < 0.5:
                        ref = matches[0]
                        cpt = ref["cpt_code"]  # Update CPT code to resolved one

            # Fallback to static reference
            if not ref:
                ref = self.CPT_REFERENCE.get(cpt)

            # Display order: partner CSV description -> curated/plain-language
            # name -> explicit "no description available" (never a guess).
            # Track which of those it was, so a reader can tell whether a name is
            # their own wording, an official CMS description, or one we wrote.
            if desc:
                resolved_desc, desc_source = desc, "bill"
            elif ref and ref.get("description"):
                resolved_desc, desc_source = ref["description"], "curated"
            elif self.code_name(cpt):
                resolved_desc = self.code_name(cpt)
                desc_source = self.code_name_source(cpt) or "authored"
            else:
                resolved_desc, desc_source = "no description available", "none"
            
            audit_entry = {
                "cpt_code": cpt,
                # What the bill says this line is (partner wording wins).
                "description": resolved_desc,
                "description_source": desc_source,
                # What the CODE means, independent of the bill's wording. Kept
                # separate so a miscoded line's own claim is never mistaken for
                # the code's definition.
                "code_name": self.code_name(cpt),
                "code_name_source": self.code_name_source(cpt),
                "billed_amount": amount,
                "status": "Clear",
                "notes": "",
                "fair_max_ref": ref["fair_max"] if ref else None,
                "medicare_max_ref": ref.get("medicare_max") if ref else None,
            }

            if ref:
                # Check for extreme pricing against the review ceiling. This is a
                # screening threshold, not a legal maximum — the naming must not
                # imply it carries any standing in a dispute.
                if amount > ref["fair_max"]:
                    audit_entry["status"] = "Overpriced"
                    diff = amount - ref["fair_max"]
                    audit_entry["notes"] = (
                        f"Billed amount exceeds the review ceiling "
                        f"(5x Medicare rate) of ${ref['fair_max']:.2f} by ${diff:.2f}."
                    )
                    has_overpricing = True
                    item_savings[idx] = max(item_savings[idx], diff)
                
                # Classify E/M codes (Evaluation and Management visits) vs procedures
                if cpt.startswith("992"):  # E/M codes
                    em_items.append((cpt, amount, ref, idx))
                else:
                    procedure_items.append((cpt, amount, ref, idx))
            else:
                audit_entry["status"] = "Not price-checked"
                audit_entry["notes"] = (
                    "No Medicare physician fee schedule rate on file for this code, "
                    "so its price was not benchmarked. Labs, drugs and supplies are "
                    "paid under separate CMS fee schedules."
                )

            audited_items.append(audit_entry)

        # Audit Check: Upcoding (High E/M visit billed alongside only minor procedures)
        # Severity-based logic applies only to codes with a known severity
        # (the curated built-ins). Price-only CMS-benchmark codes have no
        # severity and are conservatively skipped — no upcoding accusation
        # without the metadata to support it.
        for em_cpt, em_amount, em_ref, em_idx in em_items:
            em_severity = em_ref.get("severity")
            # If it's a high-severity visit (Level 5 or Level 4)
            if em_severity is not None and em_severity >= 4:
                # Check if all other procedures are known-low severity (<= 2).
                # Unknown (None) severity blocks the flag rather than assuming minor.
                if procedure_items and all(
                    (p_ref.get("severity") is not None and p_ref.get("severity") <= 2)
                    for _, _, p_ref, _ in procedure_items
                ):
                    has_upcoding = True
                    # Find a suggested lower E/M code (e.g. Level 3)
                    suggested_cpt = "99283" if em_cpt.startswith("9928") else "99214"
                    suggested_ref = None
                    if self.db:
                        suggested_ref = self.db.get_rule(suggested_cpt)
                    if not suggested_ref:
                        suggested_ref = self.CPT_REFERENCE[suggested_cpt]
                    
                    # Calculate potential savings based on downcoding to fair max of Level 3
                    current_fair_max = em_ref["fair_max"]
                    downcoded_fair_max = suggested_ref["fair_max"]
                    savings = max(em_amount - downcoded_fair_max, 0.0)
                    item_savings[em_idx] = max(item_savings[em_idx], savings)

                    findings.append({
                        "type": "Upcoding",
                        "severity": "High",
                        "message": (
                            f"Potential Upcoding on E/M visit code {em_cpt}"
                            f"{self._name_suffix(em_cpt)} (${em_amount:.2f}). "
                            f"The performed procedures are classified as minor/moderate, which does not "
                            f"support a Level {em_ref['severity']} visit. Recommended to downcode to "
                            f"{suggested_cpt} ({suggested_ref['description']}), saving up to ${savings:.2f}."
                        )
                    })
                    
                    # Update status of the E/M code in audited items
                    for item in audited_items:
                        if item["cpt_code"] == em_cpt:
                            item["status"] = "Potential Upcoding"
                            item["notes"] = f"Suspected upcoding. Recommended CPT: {suggested_cpt}."

        # Audit Check: Unbundling (Separate charges for same-day evaluation & minor procedure)
        # Bundling rules concern minor SURGICAL procedures that carry a global
        # period — not imaging, labs or other diagnostics. Only curated codes
        # carry the severity classification that marks them as such, so a
        # price-only expanded code (e.g. a chest X-ray) must never trigger this.
        curated_procedures = [
            p for p in procedure_items if p[2].get("severity") is not None
        ]
        if em_items and curated_procedures:
            has_unbundling = True
            findings.append({
                "type": "Unbundling",
                "severity": "Medium",
                "message": (
                    "Potential Unbundling/Double Billing detected. Evaluation & Management visits (E/M) "
                    "are generally bundled within the global package of minor surgical procedures. "
                    "Charging separately for both the visit and the procedure on the same day is often duplicate billing."
                )
            })
            for em_cpt, _, _, _ in em_items:
                for item in audited_items:
                    if item["cpt_code"] == em_cpt:
                        if item["status"] in ("Clear", "Not price-checked"):
                            item["status"] = "Potential Unbundling"
                            item["notes"] = "E/M visit billed same day as procedure. Check bundling rules."

        # Check for standalone overpriced items that weren't caught by upcoding
        for idx, item in enumerate(audited_items):
            if item["status"] == "Overpriced":
                # Only report as overpricing finding if not already handled by upcoding
                if not any(f["type"] == "Upcoding" and item["cpt_code"] in f["message"] for f in findings):
                    findings.append({
                        "type": "Overpricing",
                        "severity": "High",
                        "message": (
                            f"{self.code_system(item['cpt_code'])} {item['cpt_code']}"
                            f"{self._name_suffix(item['cpt_code'])} "
                            f"is billed at ${item['billed_amount']:.2f}, above the "
                            f"review ceiling (5x Medicare rate) of "
                            f"${item['fair_max_ref']:.2f}."
                            + (
                                f" Medicare's national payment for this service is "
                                f"${item['medicare_max_ref']:.2f} "
                                f"({item['billed_amount'] / item['medicare_max_ref']:.1f}x)."
                                if item.get("medicare_max_ref")
                                else ""
                            )
                        )
                    })

        suggested_savings = sum(item_savings)

        # Calculate final overall risk level
        if has_upcoding or (has_overpricing and suggested_savings > 1000):
            risk_level = "High"
        elif has_unbundling or has_overpricing:
            risk_level = "Medium"
        else:
            risk_level = "Low"

        # Generate dispute letter if issues found
        dispute_letter = ""
        if risk_level != "Low":
            dispute_letter = self._generate_dispute_letter(items, audited_items, findings, total_billed, suggested_savings)

        return {
            "provider_name": self.provider_name,
            "total_billed": total_billed,
            "suggested_savings": suggested_savings,
            "risk_level": risk_level,
            "audited_items": audited_items,
            "findings": findings,
            "dispute_letter": dispute_letter,
        }

    def _generate_dispute_letter(
        self,
        original_items: List[Dict[str, Any]],
        audited_items: List[Dict[str, Any]],
        findings: List[Dict[str, Any]],
        total_billed: float,
        suggested_savings: float,
    ) -> str:
        """Helper to generate a formatted dispute letter."""
        findings_bullets = ""
        for idx, f in enumerate(findings, 1):
            findings_bullets += f"  {idx}. [{f['type']} - {f['severity']} Risk]: {f['message']}\n"

        bill_table = ""
        for item in audited_items:
            code = item["cpt_code"]
            ref_str = (
                f" (review ceiling: ${item['fair_max_ref']:.2f})"
                if item["fair_max_ref"] else ""
            )
            # State what the code means, not what the bill claims it means. When
            # the bill's own wording differs, quote it separately rather than
            # presenting it as the code's definition - otherwise a miscoded line
            # gets its error repeated back in our own letter.
            official = self.code_name(code)
            bill_wording = item["description"] if item.get("description_source") == "bill" else None
            shown = official or item["description"]
            bill_table += (
                f"  - {self.code_system(code)} {code}: {shown} "
                f"- ${item['billed_amount']:.2f}{ref_str} [{item['status']}]\n"
            )
            if official and bill_wording and bill_wording.strip().lower() != official.strip().lower():
                bill_table += f'      (this line is described on the bill as: "{bill_wording}")\n'

        # Factual, checkable anchor: the published Medicare national payment.
        # Stated as a comparison, not as an assertion about what is owed.
        medicare_lines = ""
        for item in audited_items:
            rate = item.get("medicare_max_ref")
            if rate and item["billed_amount"] > rate:
                multiple = item["billed_amount"] / rate
                medicare_lines += (
                    f"  - {self.code_system(item['cpt_code'])} {item['cpt_code']}: "
                    f"Medicare's national payment is "
                    f"${rate:.2f}; this bill charges ${item['billed_amount']:.2f} "
                    f"({multiple:.1f}x that amount).\n"
                )
        medicare_block = (
            "Reference — published Medicare national payment amounts:\n"
            f"{medicare_lines}\n"
            "(Medicare rates are published by CMS in the Physician Fee Schedule and\n"
            "can be verified independently. They are provided as a factual reference\n"
            "point, not as a claim about the amount legally owed.)\n\n"
            if medicare_lines else ""
        )

        # Only assert what this bill actually shows. Paragraphs about coding
        # rules and the requests that follow are built from the findings that
        # were genuinely raised — a letter must never allege an issue that is
        # not present, both because it is untrue and because it hands the
        # billing department an easy dismissal.
        finding_types = {f["type"] for f in findings}
        upcoded_codes = sorted({
            item["cpt_code"] for item in audited_items
            if item["status"] == "Potential Upcoding"
        })

        rules = []
        if "Unbundling" in finding_types:
            rules.append(
                "Evaluation and Management (E/M) services are generally bundled "
                "into the procedure charge when performed on the same day."
            )
        if "Upcoding" in finding_types:
            codes = ", ".join(f"{self.code_system(c)} {c}" for c in upcoded_codes) or "the billed visit code"
            rules.append(
                "Visit levels must match the clinical severity of the condition. "
                f"The level billed on {codes} does not appear to be supported by "
                "the procedures documented on this bill."
            )
        rules_block = ""
        if rules:
            rules_block = "Under standard medical coding rules:\n" + "".join(
                f"{i}. {r}\n" for i, r in enumerate(rules, 1)
            ) + "\n"

        requests = []
        if "Upcoding" in finding_types:
            requests.append(
                "A formal coding audit of my chart and physician notes to confirm "
                "the visit level billed."
            )
        if "Unbundling" in finding_types:
            requests.append("Review of same-day charges that may be bundled.")
        if "Overpricing" in finding_types:
            requests.append(
                "Review of charges that sit far above the published Medicare "
                "national rate for the same service, as itemized above."
            )
        if not requests:
            requests.append("An itemized review of the charges identified above.")
        requests_block = "".join(f"- {r}\n" for r in requests)

        count = len(findings)
        discrepancy_phrase = (
            "one item was identified that warrants review"
            if count == 1 else
            f"{count} items were identified that warrant review"
        )

        letter = f"""Subject: Formal Billing Dispute & Audit Request - Urgent

To: {self.provider_name} Billing Department / Patients Accounts
From: Patient Advocacy / Insured Patient
Date: [Insert Date]

Dear {self.provider_name} Billing Representative,

I am writing to formally dispute the charges on my recent bill of ${total_billed:.2f} from your facility, {self.provider_name}. 

Following a review of the billed itemized codes against published Medicare payment data and standard coding conventions, {discrepancy_phrase}:

Summary of Audit Findings:
{findings_bullets}
Itemized Bill Breakdown:
{bill_table}
{medicare_block}{rules_block}Based on these findings, I request:
{requests_block}
I request that this account be placed on "Dispute Status" and all collection actions suspended while this audit is performed. I look forward to receiving a revised, corrected statement.

Sincerely,

[Your Name]
[Account/Billing Number]
[Contact Information]
"""
        return letter.strip()
